package com.regulith.gamma;

import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * Audit Dashboard & Evidence API
 */
@RestController
@RequestMapping("/api/audit")
@Slf4j
public class AuditDashboardController {

    @GetMapping("/narratives")
    public ResponseEntity<List<Map<String, Object>>> getNarratives() {
        return ResponseEntity.ok(List.of(
                Map.of(
                        "id", 1,
                        "eventType", "CODE_COMMIT",
                        "generatedAt", LocalDateTime.now().toString(),
                        "narrative", "Audit evidence auto-generated by Gamma Service Narrator Agent",
                        "controlsSatisfied", "ITGC-CM-01, ITGC-CM-02, ITGC-SD-01"
                )
        ));
    }

    @GetMapping("/dashboard")
    public ResponseEntity<Map<String, Object>> getDashboard() {
        return ResponseEntity.ok(Map.of(
                "service", "gamma-service",
                "totalNarratives", 12,
                "auditReadiness", "82%",
                "lastGenerated", LocalDateTime.now().toString(),
                "description", "Audit evidence and compliance dashboard"
        ));
    }

    @GetMapping("/health")
    public ResponseEntity<Map<String, String>> health() {
        return ResponseEntity.ok(Map.of(
                "service", "gamma-service",
                "status", "UP",
                "role", "Audit Evidence & Dashboard"
        ));
    }
}
